- name: Install docker
  hosts: public-machine
  become: yes
  vars:
    pkgstoinstall: [ libffi-dev, libssl-dev, python3, python3-pip ]
  tasks:
    - name: Install a list of packages
      apt:
        name: "{{ pkgstoinstall }}"
        update_cache: yes

    - name: Remove python-configparser package
      apt:
        name: python-configparser
        state: absent

    - name: get docker convenience script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
      args:
        creates: /home/azureuser/get-docker.sh

    - name: install docker
      shell: sh /home/azureuser/get-docker.sh
      args:
        creates: /usr/bin/docker
