- name: Copy frontend sources
  hosts: public-machine
  become: yes
  tasks:
  - name: tear down Docker Compose stack
    community.docker.docker_compose_v2:
      project_src: /home/azureuser
      files:
      - docker-compose.prod.yml
      state: absent

  - name: deploy Docker Compose stack
    community.docker.docker_compose_v2:
      project_src: /home/azureuser
      files:
      - docker-compose.prod.yml
