- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: public-machine
  tasks:
    - name: get pwd
      command: pwd
      register: result

    - name: Display the config
      debug:
        msg: "The hostname is {{ inventory_hostname}} and the pwd is {{ result.stdout }}"